### PR TITLE
fix vanilla recipe conflicts

### PR DESCRIPTION
**Pull request by Linguardium**
create a couple vanilla tags (prepping logs for future compatibility problems that may be found...not strictly necessary)
use vanilla_planks tag in vanilla crafting table overwrite
also fixed bookshelf conflicts

### CODE REVIEW

**Comment by Linguardium** [comment]
fixes #21

**Comment by AOCAWOL** [comment]
So, I have a few questions about this tag. A. is this a universally used fabric tag? I say this because if you are overriding the vanilla recipe with this tag then other fabric mods without this tag are going to not work causing major compatibility issues?

**Comment by CorgiTaco** [comment]
Have you tripled Check that this will work with other biome mods like terrestria, traverse, or any other biome mod?

**Comment by CorgiTaco** [comment]
Just tested, and this breaks modded crafting tables it seems. Terrestria no longer worked

**Comment by CorgiTaco** [comment]
Well modded planks making crafting tables(vanilla or modded)

**Comment by Linguardium** [comment]
Yeah, i did forget about other mods, going to have to rethink this

**Pull request closed without merging**
