### PR TITLE
A couple of recipe fixes

### LINKED ISSUE #448: Mossy red rock bricks recipe is erroneous
__**API/Modloader**__
Fabric

__**Describe the bug**__
Mossy red rock bricks are crafted using the stonecutter. This does not match vanilla mossy block recipes.

__**To Reproduce**__
View the mossy red rock brick recipe in REI or the code itself.

**Expected behavior**
Mossy red rock bricks would be crafted in a shapeless recipe using one red rock bricks and one vines, as per vanilla mossy whatevers recipes.
In 1.17, another recipe would be added that is the same, but using a moss block instead of vines. As of the latest snapshots, the vine recipe still exists for vanilla blocks, so the old one needn't be removed.

### LINKED ISSUE #470: Missing item in Recipe for crafting minecraft:gray_dye
**Before filling out this issue: **
**1. We only support the latest version of BYG on for Minor Bugs.**
**2. Please test BYG on its own to confirm whether or not this is a mod conflict.**

__**Mod conflict? If so, please clarify which mod is conflicting!**__
I'll provide with as much as possible, since I have no idea.  (I am using the latest version of kanpeki modpack.)

__**API/Modloader**__
Forge/Fabric?
Fabric
__**Describe the bug**__
What is the bug? Where/How does it occur? etc.
Recipe ID: byg:gray_dye, for some reason there seems to be nothing that requires it.
__**To Reproduce**__
Provide step by step instructions
Crafting anything, a split second it'll show minecraft:gray_dye as the result. (tested on a multiplayer server, and this bug is apparent. Testing on single player with the mod by itself and with the modpack does not show the bug however it still shows the recipe in a singleplayer world with the modpack.)
**Expected behavior**
It'll show the result of minecraft:gray_dye for a split second. 
**Screenshots/Videos**
If applicable, add screenshots/video to help explain your problem.

^ Recipe ID.
https://user-images.githubusercontent.com/56524051/117869753-337be580-b269-11eb-897a-96b0e46e3291.mp4

**Additional context**

**Logs**
Use: https://paste.ee/ and paste the links. if log is huge please upload those
Please provide:
Crashlog - 
Debug.log - https://paste.ee/p/BwPzC
Latest.log - https://paste.ee/p/RGRmQ

### PR DESCRIPTION
**Pull request by MarioSMB**
Removes the empty tag and recipe for gray dye, fixing #470
Fix ametrine horse armor dropping leather and string when crushed (it's crafted with purely ametrine gems!)
Fix red rock bricks and mossy red rock bricks recipes, fixes #448
Fix dacite, mossy stone, rocky stone, scoria and soapstone recipes so that they can be made with both regular crafting and stonecutting

### CODE REVIEW

**Comment by CorgiTaco** [comment]
Im very iffy with making conditioned recipes especially forge conditions since it wont work on fabric and the entire deserializer is bound to break I believe

**Comment by MarioSMB** [comment]
Ah, I'm unaware of a proper way to check for empty tags with Fabric... Would it be preferable to instead remove the gray dye placeholder recipe/tag?

**Comment by CorgiTaco** [comment]
mmmm if it isnt used for anything then yea remove it

**Comment by MarioSMB** [comment]
Alrighty, I've made that change and updated the description.

**Comment by MarioSMB** [comment]
Pardon the commit spam, I discovered a missing crafting recipe for one of the stone types and that rabbit hole led me through most of the cuttable blocks in the mod. Hopefully that's all of them covered.

**Comment by CorgiTaco** [comment]
Dw l, I just squash these things

**Pull request merged**
