### PR TITLE
Replaced imparius_mushroom_canopy6 with valid NBT file

### PR DESCRIPTION
**Pull request by m2jest1c**
Invalid file replaced with valid file from [v2.0.1.1 Beta on Modrinth](https://modrinth.com/mod/biomesyougo/version/1.19.2-2.0.1.1-fabric). Replacement is valid on IntelliJ and everything has been tested after a fresh build after recloning. Everything should be good to go.

Reference #1206

### CODE REVIEW

**Comment by CorgiTaco** [comment]
I just fixed it lol. the issue as to why your last PR wasnt identifying the change was bc I needed to add this to `.gitattributes`: https://github.com/AOCAWOL/BYG/blob/1.19.X/.gitattributes#L16

**Comment by CorgiTaco** [comment]
Thank you by the way though!

**Comment by m2jest1c** [comment]
I had to do some real weird stuff:

git rm <old file>
mv <new file> <same as old file but rename it a bit>
git stage
mv <renamed file> <original name>
git stage
git commit -a -S 
git push

This is what allowed it to identify the modification. I had taken a look at the .gitattributes but didn't want to mess with it given it's a root folder and I'm not the biggest git expert

**Comment by CorgiTaco** [comment]
weird

**Pull request closed without merging**
