### PR TITLE
Deprecation fixes

### PR DESCRIPTION
**Pull request by JT122406**
Removes Deprecated LazyLoaded Value usage
and suppresses some warnings that we can't get around

### CODE REVIEW

**Comment by Matyrobbrt** [comment]
Have you tested these changes on Forge? The usage of lazyloadedvalue was very much so intentional.

**Comment by JT122406** [comment]
> Have you tested these changes on Forge? The usage of lazyloadedvalue was very much so intentional.

I tested them in my own mod and it seems to work fine

**Comment by FinnT730** [comment]
> > Have you tested these changes on Forge? The usage of lazyloadedvalue was very much so intentional.
> 
> I tested them in my own mod and it seems to work fine

Your mod != BYG
You need to test it with _the BYG mod_

**Comment by Matyrobbrt** [comment]
I am asking because calling `#get` on registry objects on Forge too early results in NPE crashes as the objects are not yet registered. You're practically calling it on static init, which can happen at any time. If you **cannot** stand the urge of "fixing" a deprecation at least use the [BYG Lazy](https://github.com/AOCAWOL/BYG/blob/1.19.X/Common/src/main/java/potionstudios/byg/util/lazy/LazySupplier.java).
You also seem to be doing completely irrelevant changes to what your PR intends to "fix", like updating random Gradle dependencies, Forge, Fabric and adding a tag to a map (why in this PR if you already have #959 open doing the same thing?!)

**Comment by JT122406** [comment]
oh thats my bad meant to make a branch from upstream

**Pull request closed without merging**
