### PR TITLE
Update zh_cn.json

### PR DESCRIPTION
**Pull request by linzexin022**
Curseforge Credits: Godzmoline

Hi there, I have some questions which will help a lot me improve my translations if you're willing to answer! I'm not a professional mineralogist, botanist or native English speaker, therefore, your corrections for me is very important! Thank you for your patience reading and answering! The questions are as follows.
 
I'm not sure what "Basalt Barrera" actually refers to. I'm not familiar with the word "Barrera" which seems like a Mexican name word.With my first stereotyped impression of this biome in game, I think it's basalt exposed to air,then it formed a small natural dam or a barrier separating land from water. What's the exact meaning of "Barrera"?
 
What is "Dummy" biome？I checked chat records in Discord but still couln't figure it out.

What is ivis plant at The End biome？

What does "oddity" mean? The fruiting body of fungus?

What is the origin (or the combination words) of "Pendorite"（from Pendora?）, "Shulkren"(Shulker+?);"wailing garth";"Sythian"(Scythian?),"Therium"(Thorium)？
 
Thank you again for your incredibly patience!

### CODE REVIEW

**Comment by CorgiTaco** [comment]
Ignore dummy as its a placeholder biome we use for testing but it's not used anywhere.
"Oddity" means like "strange"
"Ivis" is a made up word i believe. 
"Shulkren" is related to shulkers so "shulker forest" maybe for the translation?
"Pendorite" is a made up word i believe. 
"Sythian" Im not sure
"Wailing" is like a loud cry or scream.
"Therium" uhm maybe? Im not sure.

**Comment by CorgiTaco** [comment]
Im going to merge this for the time being you can open another pr with your fixes!

**Comment by EnterFor** [comment]
@linzexin022 大大能否更新一下语言文件，好多有一些变化....ღ( ´･ᴗ･` )比心❤

**Comment by linzexin022** [comment]
> @ linzexin022大大能够更新一下语言文件，好多有一些变化....ღ（´･ᴗ･`）比心❤

好说

**Pull request merged**
