### PR TITLE
Coloured sandstone and red rock crafting fixes

### PR DESCRIPTION
**Pull request by saltyseadoggo**
This pull request contains numerous parity fixes for coloured sandstone and red rock crafting recipes across the crafting table, stonecutter and furnace. They are as follows:

- Allow red rock bricks to be crafted using a vanilla style crafting table recipe.
- Allow chiselled red rock bricks to be crafted using a vanilla style crafting table recipe.
- Allow red rock slabs/stairs/walls to be crafted from red rock using vanilla style crafting table recipes.
- Allow red rock brick slabs/stairs/walls to be crafted from red rock bricks using vanilla style crafting table recipes.
- Allow cracked red rock brick slabs/stairs/walls to be crafted from cracked red rock bricks using vanilla style crafting table recipes.
- Allow mossy red rock brick slabs/stairs/walls to be crafted from mossy red rock bricks using vanilla style crafting table recipes.
- Allow chiselled red rock brick slabs/stairs/walls to be crafted from chiselled red rock bricks using vanilla style crafting table recipes.

- Allow red rock brick slabs/stairs/walls to be stonecut from red rock in addition to red rock bricks.
- Allow chiselled red rock bricks to be stonecut from red rock in addition to red rock bricks, fixing #214.
- Allow chiselled red rock brick slabs/stairs/walls to be stonecut from red rock and red rock bricks in addition to chiselled red rock bricks.
- Replace the mossy red rock bricks stonecutting recipe with a vanilla-style crafting table recipe, fixing #218.
- Replace the cracked red rock bricks stonecutting recipe with a vanilla-style smelting recipe, fixing #213.

- Replace the smooth coloured sandstone stonecutting recipes with vanilla-style smelting recipes, fixing #202.
- Add vanilla-style crafting recipes for cut coloured sandstones, fixing #219.

Chiselled sandstone crafting table recipes are still missing. I'll try to get around to this.

In addition to this, other stone types are undoubtedly missing appropriate crafting table recipes; it seems that stones added by this mod only have stonecutting recipes for the most part.

### CODE REVIEW

**Review by CorgiTaco — CHANGES_REQUESTED** [review]
I'd appreciate if you squashed your commits as 64 commits is excessive as hell for just recipes

**Comment by saltyseadoggo** [comment]
I am afraid that I don't know how to do that. If you would be so kind as to explain, I can fix it.

**Comment by CorgiTaco** [comment]
Ah it seems github has a fancy thing for squashing.

**Comment by saltyseadoggo** [comment]
Well, it's all settled now. The chiselled sandstone crafting recipes are still missing, but I'll make a report for that.~

**Pull request merged**
