### PR TITLE
Updated to Minecraft 1.17 (Fabric)

### PR DESCRIPTION
**Pull request by KernelFreeze**
I updated the mod to compile under FabricMC 1.17 and Java 16.

Mojang revamped the world generation on 1.17, so I refactored almost everything.

### CODE REVIEW

**Comment by CorgiTaco** [comment]
There are outstanding merge conflicts here

**Comment by KernelFreeze** [comment]
> There are outstanding merge conflicts here

I think that's because the 1.17 branch is outdated, should I instead PR 1.16 branch?

**Comment by CorgiTaco** [comment]
Hm well, the fabric branch as a whole is outdated to be quite honest

**Comment by KernelFreeze** [comment]
Hmm I think I can rebase this branch to resolve the conflicts

**Comment by CorgiTaco** [comment]
yeah pr it to the 1.16 branch and I'll merge it into a 1.17 branch. this 1.17 branch quite honestly is crap so itll be deleted and replaced with your changes

**Comment by CorgiTaco** [comment]
Also feel free to join our discord so we can more easily discuss this: https://discord.gg/ShYUs4md

**Comment by KernelFreeze** [comment]
Closing this to PR again against the 1.16 branch

**Pull request closed without merging**
